name: Trigger Docs Deployment
on:
  # release:
  #   types: [published]
  push:
    branches: ["main"]
    paths:
      - '**.md'
      - '**.markdown'

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger deployment in main repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          repository: BlueAcornInc/aio-commerce-apps
          event-type: release-trigger
          client-payload: ${{ toJSON(fromJSON(format('{"repository":"{0}","tag":"{1}","release_url":"{2}","package_name":"{3}","sha":"{4}","commit_message":"{5}"}', github.repository, github.ref_name, github.event.head_commit.url, github.event.repository.name, github.sha, github.event.head_commit.message))) }}